// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Frpg2RequestMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Frpg2RequestMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace Frpg2RequestMessage {

void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto() {
  delete RequestQueryLoginServerInfo::default_instance_;
  delete RequestQueryLoginServerInfoResponse::default_instance_;
  delete RequestHandshake::default_instance_;
  delete RequestHandshakeResponse::default_instance_;
  delete GetServiceStatus::default_instance_;
  delete GetServiceStatusResponse::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_Frpg2RequestMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Frpg2RequestMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  RequestQueryLoginServerInfo::default_instance_ = new RequestQueryLoginServerInfo();
  RequestQueryLoginServerInfoResponse::default_instance_ = new RequestQueryLoginServerInfoResponse();
  RequestHandshake::default_instance_ = new RequestHandshake();
  RequestHandshakeResponse::default_instance_ = new RequestHandshakeResponse();
  GetServiceStatus::default_instance_ = new GetServiceStatus();
  GetServiceStatusResponse::default_instance_ = new GetServiceStatusResponse();
  RequestQueryLoginServerInfo::default_instance_->InitAsDefaultInstance();
  RequestQueryLoginServerInfoResponse::default_instance_->InitAsDefaultInstance();
  RequestHandshake::default_instance_->InitAsDefaultInstance();
  RequestHandshakeResponse::default_instance_->InitAsDefaultInstance();
  GetServiceStatus::default_instance_->InitAsDefaultInstance();
  GetServiceStatusResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Frpg2RequestMessage_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Frpg2RequestMessage_2eproto_once_);
void protobuf_AddDesc_Frpg2RequestMessage_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Frpg2RequestMessage_2eproto_once_,
                 &protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Frpg2RequestMessage_2eproto {
  StaticDescriptorInitializer_Frpg2RequestMessage_2eproto() {
    protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  }
} static_descriptor_initializer_Frpg2RequestMessage_2eproto_;
#endif

// ===================================================================

static ::std::string* MutableUnknownFieldsForRequestQueryLoginServerInfo(
    RequestQueryLoginServerInfo* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestQueryLoginServerInfo::kSteamidFieldNumber;
const int RequestQueryLoginServerInfo::kUnknownfieldFieldNumber;
const int RequestQueryLoginServerInfo::kVersionnumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestQueryLoginServerInfo::RequestQueryLoginServerInfo()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.RequestQueryLoginServerInfo)
}

void RequestQueryLoginServerInfo::InitAsDefaultInstance() {
}

RequestQueryLoginServerInfo::RequestQueryLoginServerInfo(const RequestQueryLoginServerInfo& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.RequestQueryLoginServerInfo)
}

void RequestQueryLoginServerInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  steamid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unknownfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  versionnum_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RequestQueryLoginServerInfo::~RequestQueryLoginServerInfo() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  SharedDtor();
}

void RequestQueryLoginServerInfo::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  steamid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unknownfield_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void RequestQueryLoginServerInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RequestQueryLoginServerInfo& RequestQueryLoginServerInfo::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

RequestQueryLoginServerInfo* RequestQueryLoginServerInfo::default_instance_ = NULL;

RequestQueryLoginServerInfo* RequestQueryLoginServerInfo::New(::google::protobuf::Arena* arena) const {
  RequestQueryLoginServerInfo* n = new RequestQueryLoginServerInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestQueryLoginServerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_steamid()) {
      steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_unknownfield()) {
      unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    versionnum_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool RequestQueryLoginServerInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForRequestQueryLoginServerInfo, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string steamid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_steamid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_unknownfield;
        break;
      }

      // optional string unknownfield = 2;
      case 2: {
        if (tag == 18) {
         parse_unknownfield:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unknownfield()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_versionnum;
        break;
      }

      // required int64 versionnum = 3;
      case 3: {
        if (tag == 24) {
         parse_versionnum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &versionnum_)));
          set_has_versionnum();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  return false;
#undef DO_
}

void RequestQueryLoginServerInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  // required string steamid = 1;
  if (has_steamid()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->steamid(), output);
  }

  // optional string unknownfield = 2;
  if (has_unknownfield()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->unknownfield(), output);
  }

  // required int64 versionnum = 3;
  if (has_versionnum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->versionnum(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.RequestQueryLoginServerInfo)
}

int RequestQueryLoginServerInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  int total_size = 0;

  if (has_steamid()) {
    // required string steamid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());
  }

  if (has_versionnum()) {
    // required int64 versionnum = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());
  }

  return total_size;
}
int RequestQueryLoginServerInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required string steamid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());

    // required int64 versionnum = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional string unknownfield = 2;
  if (has_unknownfield()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->unknownfield());
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestQueryLoginServerInfo::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RequestQueryLoginServerInfo*>(&from));
}

void RequestQueryLoginServerInfo::MergeFrom(const RequestQueryLoginServerInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_steamid()) {
      set_has_steamid();
      steamid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.steamid_);
    }
    if (from.has_unknownfield()) {
      set_has_unknownfield();
      unknownfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.unknownfield_);
    }
    if (from.has_versionnum()) {
      set_versionnum(from.versionnum());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void RequestQueryLoginServerInfo::CopyFrom(const RequestQueryLoginServerInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.RequestQueryLoginServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestQueryLoginServerInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;

  return true;
}

void RequestQueryLoginServerInfo::Swap(RequestQueryLoginServerInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestQueryLoginServerInfo::InternalSwap(RequestQueryLoginServerInfo* other) {
  steamid_.Swap(&other->steamid_);
  unknownfield_.Swap(&other->unknownfield_);
  std::swap(versionnum_, other->versionnum_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string RequestQueryLoginServerInfo::GetTypeName() const {
  return "Frpg2RequestMessage.RequestQueryLoginServerInfo";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestQueryLoginServerInfo

// required string steamid = 1;
bool RequestQueryLoginServerInfo::has_steamid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void RequestQueryLoginServerInfo::set_has_steamid() {
  _has_bits_[0] |= 0x00000001u;
}
void RequestQueryLoginServerInfo::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000001u;
}
void RequestQueryLoginServerInfo::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
 const ::std::string& RequestQueryLoginServerInfo::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfo::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
 void RequestQueryLoginServerInfo::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
 void RequestQueryLoginServerInfo::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
 ::std::string* RequestQueryLoginServerInfo::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestQueryLoginServerInfo::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfo::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}

// optional string unknownfield = 2;
bool RequestQueryLoginServerInfo::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void RequestQueryLoginServerInfo::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000002u;
}
void RequestQueryLoginServerInfo::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000002u;
}
void RequestQueryLoginServerInfo::clear_unknownfield() {
  unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_unknownfield();
}
 const ::std::string& RequestQueryLoginServerInfo::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  return unknownfield_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfo::set_unknownfield(const ::std::string& value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
 void RequestQueryLoginServerInfo::set_unknownfield(const char* value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
 void RequestQueryLoginServerInfo::set_unknownfield(const char* value, size_t size) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
 ::std::string* RequestQueryLoginServerInfo::mutable_unknownfield() {
  set_has_unknownfield();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  return unknownfield_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestQueryLoginServerInfo::release_unknownfield() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  clear_has_unknownfield();
  return unknownfield_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfo::set_allocated_unknownfield(::std::string* unknownfield) {
  if (unknownfield != NULL) {
    set_has_unknownfield();
  } else {
    clear_has_unknownfield();
  }
  unknownfield_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), unknownfield);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}

// required int64 versionnum = 3;
bool RequestQueryLoginServerInfo::has_versionnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void RequestQueryLoginServerInfo::set_has_versionnum() {
  _has_bits_[0] |= 0x00000004u;
}
void RequestQueryLoginServerInfo::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000004u;
}
void RequestQueryLoginServerInfo::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
 ::google::protobuf::int64 RequestQueryLoginServerInfo::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.versionnum)
  return versionnum_;
}
 void RequestQueryLoginServerInfo::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.versionnum)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

static ::std::string* MutableUnknownFieldsForRequestQueryLoginServerInfoResponse(
    RequestQueryLoginServerInfoResponse* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestQueryLoginServerInfoResponse::kPortFieldNumber;
const int RequestQueryLoginServerInfoResponse::kServeripFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestQueryLoginServerInfoResponse::RequestQueryLoginServerInfoResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
}

void RequestQueryLoginServerInfoResponse::InitAsDefaultInstance() {
}

RequestQueryLoginServerInfoResponse::RequestQueryLoginServerInfoResponse(const RequestQueryLoginServerInfoResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
}

void RequestQueryLoginServerInfoResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = GOOGLE_LONGLONG(0);
  serverip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RequestQueryLoginServerInfoResponse::~RequestQueryLoginServerInfoResponse() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  SharedDtor();
}

void RequestQueryLoginServerInfoResponse::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  serverip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void RequestQueryLoginServerInfoResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RequestQueryLoginServerInfoResponse& RequestQueryLoginServerInfoResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

RequestQueryLoginServerInfoResponse* RequestQueryLoginServerInfoResponse::default_instance_ = NULL;

RequestQueryLoginServerInfoResponse* RequestQueryLoginServerInfoResponse::New(::google::protobuf::Arena* arena) const {
  RequestQueryLoginServerInfoResponse* n = new RequestQueryLoginServerInfoResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestQueryLoginServerInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  if (_has_bits_[0 / 32] & 3u) {
    port_ = GOOGLE_LONGLONG(0);
    if (has_serverip()) {
      serverip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool RequestQueryLoginServerInfoResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForRequestQueryLoginServerInfoResponse, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 port = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_serverip;
        break;
      }

      // required string serverip = 2;
      case 2: {
        if (tag == 18) {
         parse_serverip:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_serverip()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  return false;
#undef DO_
}

void RequestQueryLoginServerInfoResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  // required int64 port = 1;
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->port(), output);
  }

  // required string serverip = 2;
  if (has_serverip()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->serverip(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
}

int RequestQueryLoginServerInfoResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  int total_size = 0;

  if (has_port()) {
    // required int64 port = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->port());
  }

  if (has_serverip()) {
    // required string serverip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->serverip());
  }

  return total_size;
}
int RequestQueryLoginServerInfoResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int64 port = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->port());

    // required string serverip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->serverip());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestQueryLoginServerInfoResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RequestQueryLoginServerInfoResponse*>(&from));
}

void RequestQueryLoginServerInfoResponse::MergeFrom(const RequestQueryLoginServerInfoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_port()) {
      set_port(from.port());
    }
    if (from.has_serverip()) {
      set_has_serverip();
      serverip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.serverip_);
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void RequestQueryLoginServerInfoResponse::CopyFrom(const RequestQueryLoginServerInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestQueryLoginServerInfoResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void RequestQueryLoginServerInfoResponse::Swap(RequestQueryLoginServerInfoResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestQueryLoginServerInfoResponse::InternalSwap(RequestQueryLoginServerInfoResponse* other) {
  std::swap(port_, other->port_);
  serverip_.Swap(&other->serverip_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string RequestQueryLoginServerInfoResponse::GetTypeName() const {
  return "Frpg2RequestMessage.RequestQueryLoginServerInfoResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestQueryLoginServerInfoResponse

// required int64 port = 1;
bool RequestQueryLoginServerInfoResponse::has_port() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void RequestQueryLoginServerInfoResponse::set_has_port() {
  _has_bits_[0] |= 0x00000001u;
}
void RequestQueryLoginServerInfoResponse::clear_has_port() {
  _has_bits_[0] &= ~0x00000001u;
}
void RequestQueryLoginServerInfoResponse::clear_port() {
  port_ = GOOGLE_LONGLONG(0);
  clear_has_port();
}
 ::google::protobuf::int64 RequestQueryLoginServerInfoResponse::port() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.port)
  return port_;
}
 void RequestQueryLoginServerInfoResponse::set_port(::google::protobuf::int64 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.port)
}

// required string serverip = 2;
bool RequestQueryLoginServerInfoResponse::has_serverip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void RequestQueryLoginServerInfoResponse::set_has_serverip() {
  _has_bits_[0] |= 0x00000002u;
}
void RequestQueryLoginServerInfoResponse::clear_has_serverip() {
  _has_bits_[0] &= ~0x00000002u;
}
void RequestQueryLoginServerInfoResponse::clear_serverip() {
  serverip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_serverip();
}
 const ::std::string& RequestQueryLoginServerInfoResponse::serverip() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  return serverip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfoResponse::set_serverip(const ::std::string& value) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
 void RequestQueryLoginServerInfoResponse::set_serverip(const char* value) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
 void RequestQueryLoginServerInfoResponse::set_serverip(const char* value, size_t size) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
 ::std::string* RequestQueryLoginServerInfoResponse::mutable_serverip() {
  set_has_serverip();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  return serverip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestQueryLoginServerInfoResponse::release_serverip() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  clear_has_serverip();
  return serverip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestQueryLoginServerInfoResponse::set_allocated_serverip(::std::string* serverip) {
  if (serverip != NULL) {
    set_has_serverip();
  } else {
    clear_has_serverip();
  }
  serverip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serverip);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

static ::std::string* MutableUnknownFieldsForRequestHandshake(
    RequestHandshake* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestHandshake::kAescwckeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestHandshake::RequestHandshake()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.RequestHandshake)
}

void RequestHandshake::InitAsDefaultInstance() {
}

RequestHandshake::RequestHandshake(const RequestHandshake& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.RequestHandshake)
}

void RequestHandshake::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  aescwckey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RequestHandshake::~RequestHandshake() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.RequestHandshake)
  SharedDtor();
}

void RequestHandshake::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  aescwckey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void RequestHandshake::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RequestHandshake& RequestHandshake::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

RequestHandshake* RequestHandshake::default_instance_ = NULL;

RequestHandshake* RequestHandshake::New(::google::protobuf::Arena* arena) const {
  RequestHandshake* n = new RequestHandshake;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestHandshake::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.RequestHandshake)
  if (has_aescwckey()) {
    aescwckey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool RequestHandshake::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForRequestHandshake, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.RequestHandshake)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string aescwckey = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_aescwckey()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.RequestHandshake)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.RequestHandshake)
  return false;
#undef DO_
}

void RequestHandshake::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.RequestHandshake)
  // required string aescwckey = 1;
  if (has_aescwckey()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->aescwckey(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.RequestHandshake)
}

int RequestHandshake::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.RequestHandshake)
  int total_size = 0;

  // required string aescwckey = 1;
  if (has_aescwckey()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->aescwckey());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestHandshake::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RequestHandshake*>(&from));
}

void RequestHandshake::MergeFrom(const RequestHandshake& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.RequestHandshake)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_aescwckey()) {
      set_has_aescwckey();
      aescwckey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.aescwckey_);
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void RequestHandshake::CopyFrom(const RequestHandshake& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.RequestHandshake)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestHandshake::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void RequestHandshake::Swap(RequestHandshake* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestHandshake::InternalSwap(RequestHandshake* other) {
  aescwckey_.Swap(&other->aescwckey_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string RequestHandshake::GetTypeName() const {
  return "Frpg2RequestMessage.RequestHandshake";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestHandshake

// required string aescwckey = 1;
bool RequestHandshake::has_aescwckey() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void RequestHandshake::set_has_aescwckey() {
  _has_bits_[0] |= 0x00000001u;
}
void RequestHandshake::clear_has_aescwckey() {
  _has_bits_[0] &= ~0x00000001u;
}
void RequestHandshake::clear_aescwckey() {
  aescwckey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_aescwckey();
}
 const ::std::string& RequestHandshake::aescwckey() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestHandshake.aescwckey)
  return aescwckey_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestHandshake::set_aescwckey(const ::std::string& value) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
 void RequestHandshake::set_aescwckey(const char* value) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
 void RequestHandshake::set_aescwckey(const char* value, size_t size) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
 ::std::string* RequestHandshake::mutable_aescwckey() {
  set_has_aescwckey();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestHandshake.aescwckey)
  return aescwckey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestHandshake::release_aescwckey() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestHandshake.aescwckey)
  clear_has_aescwckey();
  return aescwckey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestHandshake::set_allocated_aescwckey(::std::string* aescwckey) {
  if (aescwckey != NULL) {
    set_has_aescwckey();
  } else {
    clear_has_aescwckey();
  }
  aescwckey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), aescwckey);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestHandshake.aescwckey)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

static ::std::string* MutableUnknownFieldsForRequestHandshakeResponse(
    RequestHandshakeResponse* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestHandshakeResponse::RequestHandshakeResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.RequestHandshakeResponse)
}

void RequestHandshakeResponse::InitAsDefaultInstance() {
}

RequestHandshakeResponse::RequestHandshakeResponse(const RequestHandshakeResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.RequestHandshakeResponse)
}

void RequestHandshakeResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RequestHandshakeResponse::~RequestHandshakeResponse() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.RequestHandshakeResponse)
  SharedDtor();
}

void RequestHandshakeResponse::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void RequestHandshakeResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RequestHandshakeResponse& RequestHandshakeResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

RequestHandshakeResponse* RequestHandshakeResponse::default_instance_ = NULL;

RequestHandshakeResponse* RequestHandshakeResponse::New(::google::protobuf::Arena* arena) const {
  RequestHandshakeResponse* n = new RequestHandshakeResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestHandshakeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.RequestHandshakeResponse)
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool RequestHandshakeResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForRequestHandshakeResponse, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.RequestHandshakeResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.RequestHandshakeResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.RequestHandshakeResponse)
  return false;
#undef DO_
}

void RequestHandshakeResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.RequestHandshakeResponse)
  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.RequestHandshakeResponse)
}

int RequestHandshakeResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.RequestHandshakeResponse)
  int total_size = 0;

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestHandshakeResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RequestHandshakeResponse*>(&from));
}

void RequestHandshakeResponse::MergeFrom(const RequestHandshakeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.RequestHandshakeResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void RequestHandshakeResponse::CopyFrom(const RequestHandshakeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.RequestHandshakeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestHandshakeResponse::IsInitialized() const {

  return true;
}

void RequestHandshakeResponse::Swap(RequestHandshakeResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestHandshakeResponse::InternalSwap(RequestHandshakeResponse* other) {
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string RequestHandshakeResponse::GetTypeName() const {
  return "Frpg2RequestMessage.RequestHandshakeResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestHandshakeResponse

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

static ::std::string* MutableUnknownFieldsForGetServiceStatus(
    GetServiceStatus* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetServiceStatus::kIdFieldNumber;
const int GetServiceStatus::kSteamidFieldNumber;
const int GetServiceStatus::kUnknownfieldFieldNumber;
const int GetServiceStatus::kVersionnumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetServiceStatus::GetServiceStatus()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.GetServiceStatus)
}

void GetServiceStatus::InitAsDefaultInstance() {
}

GetServiceStatus::GetServiceStatus(const GetServiceStatus& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.GetServiceStatus)
}

void GetServiceStatus::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = GOOGLE_LONGLONG(0);
  steamid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unknownfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  versionnum_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GetServiceStatus::~GetServiceStatus() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.GetServiceStatus)
  SharedDtor();
}

void GetServiceStatus::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  steamid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unknownfield_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GetServiceStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GetServiceStatus& GetServiceStatus::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

GetServiceStatus* GetServiceStatus::default_instance_ = NULL;

GetServiceStatus* GetServiceStatus::New(::google::protobuf::Arena* arena) const {
  GetServiceStatus* n = new GetServiceStatus;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetServiceStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.GetServiceStatus)
  if (_has_bits_[0 / 32] & 15u) {
    id_ = GOOGLE_LONGLONG(0);
    if (has_steamid()) {
      steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_unknownfield()) {
      unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    versionnum_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool GetServiceStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForGetServiceStatus, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.GetServiceStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_steamid;
        break;
      }

      // required string steamid = 2;
      case 2: {
        if (tag == 18) {
         parse_steamid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_steamid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_unknownfield;
        break;
      }

      // optional string unknownfield = 3;
      case 3: {
        if (tag == 26) {
         parse_unknownfield:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unknownfield()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_versionnum;
        break;
      }

      // required int64 versionnum = 4;
      case 4: {
        if (tag == 32) {
         parse_versionnum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &versionnum_)));
          set_has_versionnum();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.GetServiceStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.GetServiceStatus)
  return false;
#undef DO_
}

void GetServiceStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.GetServiceStatus)
  // required int64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  // required string steamid = 2;
  if (has_steamid()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->steamid(), output);
  }

  // optional string unknownfield = 3;
  if (has_unknownfield()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->unknownfield(), output);
  }

  // required int64 versionnum = 4;
  if (has_versionnum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->versionnum(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.GetServiceStatus)
}

int GetServiceStatus::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Frpg2RequestMessage.GetServiceStatus)
  int total_size = 0;

  if (has_id()) {
    // required int64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  if (has_steamid()) {
    // required string steamid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());
  }

  if (has_versionnum()) {
    // required int64 versionnum = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());
  }

  return total_size;
}
int GetServiceStatus::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.GetServiceStatus)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000b) ^ 0x0000000b) == 0) {  // All required fields are present.
    // required int64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());

    // required string steamid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());

    // required int64 versionnum = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional string unknownfield = 3;
  if (has_unknownfield()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->unknownfield());
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetServiceStatus::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GetServiceStatus*>(&from));
}

void GetServiceStatus::MergeFrom(const GetServiceStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.GetServiceStatus)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_steamid()) {
      set_has_steamid();
      steamid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.steamid_);
    }
    if (from.has_unknownfield()) {
      set_has_unknownfield();
      unknownfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.unknownfield_);
    }
    if (from.has_versionnum()) {
      set_versionnum(from.versionnum());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void GetServiceStatus::CopyFrom(const GetServiceStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.GetServiceStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetServiceStatus::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;

  return true;
}

void GetServiceStatus::Swap(GetServiceStatus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetServiceStatus::InternalSwap(GetServiceStatus* other) {
  std::swap(id_, other->id_);
  steamid_.Swap(&other->steamid_);
  unknownfield_.Swap(&other->unknownfield_);
  std::swap(versionnum_, other->versionnum_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string GetServiceStatus::GetTypeName() const {
  return "Frpg2RequestMessage.GetServiceStatus";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetServiceStatus

// required int64 id = 1;
bool GetServiceStatus::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GetServiceStatus::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void GetServiceStatus::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void GetServiceStatus::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
 ::google::protobuf::int64 GetServiceStatus::id() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.id)
  return id_;
}
 void GetServiceStatus::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.id)
}

// required string steamid = 2;
bool GetServiceStatus::has_steamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void GetServiceStatus::set_has_steamid() {
  _has_bits_[0] |= 0x00000002u;
}
void GetServiceStatus::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000002u;
}
void GetServiceStatus::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
 const ::std::string& GetServiceStatus::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatus::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.steamid)
}
 void GetServiceStatus::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatus.steamid)
}
 void GetServiceStatus::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatus.steamid)
}
 ::std::string* GetServiceStatus::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatus.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetServiceStatus::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatus.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatus::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatus.steamid)
}

// optional string unknownfield = 3;
bool GetServiceStatus::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void GetServiceStatus::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000004u;
}
void GetServiceStatus::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000004u;
}
void GetServiceStatus::clear_unknownfield() {
  unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_unknownfield();
}
 const ::std::string& GetServiceStatus::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  return unknownfield_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatus::set_unknownfield(const ::std::string& value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
 void GetServiceStatus::set_unknownfield(const char* value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
 void GetServiceStatus::set_unknownfield(const char* value, size_t size) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
 ::std::string* GetServiceStatus::mutable_unknownfield() {
  set_has_unknownfield();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  return unknownfield_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetServiceStatus::release_unknownfield() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  clear_has_unknownfield();
  return unknownfield_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatus::set_allocated_unknownfield(::std::string* unknownfield) {
  if (unknownfield != NULL) {
    set_has_unknownfield();
  } else {
    clear_has_unknownfield();
  }
  unknownfield_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), unknownfield);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}

// required int64 versionnum = 4;
bool GetServiceStatus::has_versionnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void GetServiceStatus::set_has_versionnum() {
  _has_bits_[0] |= 0x00000008u;
}
void GetServiceStatus::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000008u;
}
void GetServiceStatus::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
 ::google::protobuf::int64 GetServiceStatus::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.versionnum)
  return versionnum_;
}
 void GetServiceStatus::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.versionnum)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

static ::std::string* MutableUnknownFieldsForGetServiceStatusResponse(
    GetServiceStatusResponse* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetServiceStatusResponse::kIdFieldNumber;
const int GetServiceStatusResponse::kSteamidFieldNumber;
const int GetServiceStatusResponse::kUnknownfieldFieldNumber;
const int GetServiceStatusResponse::kVersionnumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetServiceStatusResponse::GetServiceStatusResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Frpg2RequestMessage.GetServiceStatusResponse)
}

void GetServiceStatusResponse::InitAsDefaultInstance() {
}

GetServiceStatusResponse::GetServiceStatusResponse(const GetServiceStatusResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Frpg2RequestMessage.GetServiceStatusResponse)
}

void GetServiceStatusResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = GOOGLE_LONGLONG(0);
  steamid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unknownfield_ = GOOGLE_LONGLONG(0);
  versionnum_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GetServiceStatusResponse::~GetServiceStatusResponse() {
  // @@protoc_insertion_point(destructor:Frpg2RequestMessage.GetServiceStatusResponse)
  SharedDtor();
}

void GetServiceStatusResponse::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  steamid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GetServiceStatusResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GetServiceStatusResponse& GetServiceStatusResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_Frpg2RequestMessage_2eproto();
#endif
  return *default_instance_;
}

GetServiceStatusResponse* GetServiceStatusResponse::default_instance_ = NULL;

GetServiceStatusResponse* GetServiceStatusResponse::New(::google::protobuf::Arena* arena) const {
  GetServiceStatusResponse* n = new GetServiceStatusResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetServiceStatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Frpg2RequestMessage.GetServiceStatusResponse)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(GetServiceStatusResponse, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<GetServiceStatusResponse*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 15u) {
    ZR_(unknownfield_, versionnum_);
    id_ = GOOGLE_LONGLONG(0);
    if (has_steamid()) {
      steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool GetServiceStatusResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForGetServiceStatusResponse, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:Frpg2RequestMessage.GetServiceStatusResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_steamid;
        break;
      }

      // required string steamid = 2;
      case 2: {
        if (tag == 18) {
         parse_steamid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_steamid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_unknownfield;
        break;
      }

      // required int64 unknownfield = 3;
      case 3: {
        if (tag == 24) {
         parse_unknownfield:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &unknownfield_)));
          set_has_unknownfield();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_versionnum;
        break;
      }

      // required int64 versionnum = 4;
      case 4: {
        if (tag == 32) {
         parse_versionnum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &versionnum_)));
          set_has_versionnum();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Frpg2RequestMessage.GetServiceStatusResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Frpg2RequestMessage.GetServiceStatusResponse)
  return false;
#undef DO_
}

void GetServiceStatusResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Frpg2RequestMessage.GetServiceStatusResponse)
  // required int64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  // required string steamid = 2;
  if (has_steamid()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->steamid(), output);
  }

  // required int64 unknownfield = 3;
  if (has_unknownfield()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->unknownfield(), output);
  }

  // required int64 versionnum = 4;
  if (has_versionnum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->versionnum(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:Frpg2RequestMessage.GetServiceStatusResponse)
}

int GetServiceStatusResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Frpg2RequestMessage.GetServiceStatusResponse)
  int total_size = 0;

  if (has_id()) {
    // required int64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  if (has_steamid()) {
    // required string steamid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());
  }

  if (has_unknownfield()) {
    // required int64 unknownfield = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->unknownfield());
  }

  if (has_versionnum()) {
    // required int64 versionnum = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());
  }

  return total_size;
}
int GetServiceStatusResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Frpg2RequestMessage.GetServiceStatusResponse)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required int64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());

    // required string steamid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->steamid());

    // required int64 unknownfield = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->unknownfield());

    // required int64 versionnum = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->versionnum());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetServiceStatusResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GetServiceStatusResponse*>(&from));
}

void GetServiceStatusResponse::MergeFrom(const GetServiceStatusResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Frpg2RequestMessage.GetServiceStatusResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_steamid()) {
      set_has_steamid();
      steamid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.steamid_);
    }
    if (from.has_unknownfield()) {
      set_unknownfield(from.unknownfield());
    }
    if (from.has_versionnum()) {
      set_versionnum(from.versionnum());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void GetServiceStatusResponse::CopyFrom(const GetServiceStatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Frpg2RequestMessage.GetServiceStatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetServiceStatusResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void GetServiceStatusResponse::Swap(GetServiceStatusResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetServiceStatusResponse::InternalSwap(GetServiceStatusResponse* other) {
  std::swap(id_, other->id_);
  steamid_.Swap(&other->steamid_);
  std::swap(unknownfield_, other->unknownfield_);
  std::swap(versionnum_, other->versionnum_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string GetServiceStatusResponse::GetTypeName() const {
  return "Frpg2RequestMessage.GetServiceStatusResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetServiceStatusResponse

// required int64 id = 1;
bool GetServiceStatusResponse::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GetServiceStatusResponse::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void GetServiceStatusResponse::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void GetServiceStatusResponse::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
 ::google::protobuf::int64 GetServiceStatusResponse::id() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.id)
  return id_;
}
 void GetServiceStatusResponse::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.id)
}

// required string steamid = 2;
bool GetServiceStatusResponse::has_steamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void GetServiceStatusResponse::set_has_steamid() {
  _has_bits_[0] |= 0x00000002u;
}
void GetServiceStatusResponse::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000002u;
}
void GetServiceStatusResponse::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
 const ::std::string& GetServiceStatusResponse::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatusResponse::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
 void GetServiceStatusResponse::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
 void GetServiceStatusResponse::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
 ::std::string* GetServiceStatusResponse::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetServiceStatusResponse::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetServiceStatusResponse::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}

// required int64 unknownfield = 3;
bool GetServiceStatusResponse::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void GetServiceStatusResponse::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000004u;
}
void GetServiceStatusResponse::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000004u;
}
void GetServiceStatusResponse::clear_unknownfield() {
  unknownfield_ = GOOGLE_LONGLONG(0);
  clear_has_unknownfield();
}
 ::google::protobuf::int64 GetServiceStatusResponse::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.unknownfield)
  return unknownfield_;
}
 void GetServiceStatusResponse::set_unknownfield(::google::protobuf::int64 value) {
  set_has_unknownfield();
  unknownfield_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.unknownfield)
}

// required int64 versionnum = 4;
bool GetServiceStatusResponse::has_versionnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void GetServiceStatusResponse::set_has_versionnum() {
  _has_bits_[0] |= 0x00000008u;
}
void GetServiceStatusResponse::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000008u;
}
void GetServiceStatusResponse::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
 ::google::protobuf::int64 GetServiceStatusResponse::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.versionnum)
  return versionnum_;
}
 void GetServiceStatusResponse::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.versionnum)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Frpg2RequestMessage

// @@protoc_insertion_point(global_scope)
