// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Frpg2RequestMessage.proto

#ifndef PROTOBUF_Frpg2RequestMessage_2eproto__INCLUDED
#define PROTOBUF_Frpg2RequestMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace Frpg2RequestMessage {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Frpg2RequestMessage_2eproto();
void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

class GetServiceStatus;
class GetServiceStatusResponse;
class RequestHandshake;
class RequestHandshakeResponse;
class RequestQueryLoginServerInfo;
class RequestQueryLoginServerInfoResponse;

// ===================================================================

class RequestQueryLoginServerInfo : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.RequestQueryLoginServerInfo) */ {
 public:
  RequestQueryLoginServerInfo();
  virtual ~RequestQueryLoginServerInfo();

  RequestQueryLoginServerInfo(const RequestQueryLoginServerInfo& from);

  inline RequestQueryLoginServerInfo& operator=(const RequestQueryLoginServerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const RequestQueryLoginServerInfo& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestQueryLoginServerInfo* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestQueryLoginServerInfo* other);

  // implements Message ----------------------------------------------

  inline RequestQueryLoginServerInfo* New() const { return New(NULL); }

  RequestQueryLoginServerInfo* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestQueryLoginServerInfo& from);
  void MergeFrom(const RequestQueryLoginServerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestQueryLoginServerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string steamid = 1;
  bool has_steamid() const;
  void clear_steamid();
  static const int kSteamidFieldNumber = 1;
  const ::std::string& steamid() const;
  void set_steamid(const ::std::string& value);
  void set_steamid(const char* value);
  void set_steamid(const char* value, size_t size);
  ::std::string* mutable_steamid();
  ::std::string* release_steamid();
  void set_allocated_steamid(::std::string* steamid);

  // optional string unknownfield = 2;
  bool has_unknownfield() const;
  void clear_unknownfield();
  static const int kUnknownfieldFieldNumber = 2;
  const ::std::string& unknownfield() const;
  void set_unknownfield(const ::std::string& value);
  void set_unknownfield(const char* value);
  void set_unknownfield(const char* value, size_t size);
  ::std::string* mutable_unknownfield();
  ::std::string* release_unknownfield();
  void set_allocated_unknownfield(::std::string* unknownfield);

  // required int64 versionnum = 3;
  bool has_versionnum() const;
  void clear_versionnum();
  static const int kVersionnumFieldNumber = 3;
  ::google::protobuf::int64 versionnum() const;
  void set_versionnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.RequestQueryLoginServerInfo)
 private:
  inline void set_has_steamid();
  inline void clear_has_steamid();
  inline void set_has_unknownfield();
  inline void clear_has_unknownfield();
  inline void set_has_versionnum();
  inline void clear_has_versionnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr steamid_;
  ::google::protobuf::internal::ArenaStringPtr unknownfield_;
  ::google::protobuf::int64 versionnum_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static RequestQueryLoginServerInfo* default_instance_;
};
// -------------------------------------------------------------------

class RequestQueryLoginServerInfoResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse) */ {
 public:
  RequestQueryLoginServerInfoResponse();
  virtual ~RequestQueryLoginServerInfoResponse();

  RequestQueryLoginServerInfoResponse(const RequestQueryLoginServerInfoResponse& from);

  inline RequestQueryLoginServerInfoResponse& operator=(const RequestQueryLoginServerInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const RequestQueryLoginServerInfoResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestQueryLoginServerInfoResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestQueryLoginServerInfoResponse* other);

  // implements Message ----------------------------------------------

  inline RequestQueryLoginServerInfoResponse* New() const { return New(NULL); }

  RequestQueryLoginServerInfoResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestQueryLoginServerInfoResponse& from);
  void MergeFrom(const RequestQueryLoginServerInfoResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestQueryLoginServerInfoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 port = 1;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 1;
  ::google::protobuf::int64 port() const;
  void set_port(::google::protobuf::int64 value);

  // required string serverip = 2;
  bool has_serverip() const;
  void clear_serverip();
  static const int kServeripFieldNumber = 2;
  const ::std::string& serverip() const;
  void set_serverip(const ::std::string& value);
  void set_serverip(const char* value);
  void set_serverip(const char* value, size_t size);
  ::std::string* mutable_serverip();
  ::std::string* release_serverip();
  void set_allocated_serverip(::std::string* serverip);

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse)
 private:
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_serverip();
  inline void clear_has_serverip();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 port_;
  ::google::protobuf::internal::ArenaStringPtr serverip_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static RequestQueryLoginServerInfoResponse* default_instance_;
};
// -------------------------------------------------------------------

class RequestHandshake : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.RequestHandshake) */ {
 public:
  RequestHandshake();
  virtual ~RequestHandshake();

  RequestHandshake(const RequestHandshake& from);

  inline RequestHandshake& operator=(const RequestHandshake& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const RequestHandshake& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestHandshake* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestHandshake* other);

  // implements Message ----------------------------------------------

  inline RequestHandshake* New() const { return New(NULL); }

  RequestHandshake* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestHandshake& from);
  void MergeFrom(const RequestHandshake& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestHandshake* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string aescwckey = 1;
  bool has_aescwckey() const;
  void clear_aescwckey();
  static const int kAescwckeyFieldNumber = 1;
  const ::std::string& aescwckey() const;
  void set_aescwckey(const ::std::string& value);
  void set_aescwckey(const char* value);
  void set_aescwckey(const char* value, size_t size);
  ::std::string* mutable_aescwckey();
  ::std::string* release_aescwckey();
  void set_allocated_aescwckey(::std::string* aescwckey);

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.RequestHandshake)
 private:
  inline void set_has_aescwckey();
  inline void clear_has_aescwckey();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr aescwckey_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static RequestHandshake* default_instance_;
};
// -------------------------------------------------------------------

class RequestHandshakeResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.RequestHandshakeResponse) */ {
 public:
  RequestHandshakeResponse();
  virtual ~RequestHandshakeResponse();

  RequestHandshakeResponse(const RequestHandshakeResponse& from);

  inline RequestHandshakeResponse& operator=(const RequestHandshakeResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const RequestHandshakeResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestHandshakeResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestHandshakeResponse* other);

  // implements Message ----------------------------------------------

  inline RequestHandshakeResponse* New() const { return New(NULL); }

  RequestHandshakeResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestHandshakeResponse& from);
  void MergeFrom(const RequestHandshakeResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestHandshakeResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.RequestHandshakeResponse)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static RequestHandshakeResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetServiceStatus : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.GetServiceStatus) */ {
 public:
  GetServiceStatus();
  virtual ~GetServiceStatus();

  GetServiceStatus(const GetServiceStatus& from);

  inline GetServiceStatus& operator=(const GetServiceStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const GetServiceStatus& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetServiceStatus* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetServiceStatus* other);

  // implements Message ----------------------------------------------

  inline GetServiceStatus* New() const { return New(NULL); }

  GetServiceStatus* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GetServiceStatus& from);
  void MergeFrom(const GetServiceStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetServiceStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // required string steamid = 2;
  bool has_steamid() const;
  void clear_steamid();
  static const int kSteamidFieldNumber = 2;
  const ::std::string& steamid() const;
  void set_steamid(const ::std::string& value);
  void set_steamid(const char* value);
  void set_steamid(const char* value, size_t size);
  ::std::string* mutable_steamid();
  ::std::string* release_steamid();
  void set_allocated_steamid(::std::string* steamid);

  // optional string unknownfield = 3;
  bool has_unknownfield() const;
  void clear_unknownfield();
  static const int kUnknownfieldFieldNumber = 3;
  const ::std::string& unknownfield() const;
  void set_unknownfield(const ::std::string& value);
  void set_unknownfield(const char* value);
  void set_unknownfield(const char* value, size_t size);
  ::std::string* mutable_unknownfield();
  ::std::string* release_unknownfield();
  void set_allocated_unknownfield(::std::string* unknownfield);

  // required int64 versionnum = 4;
  bool has_versionnum() const;
  void clear_versionnum();
  static const int kVersionnumFieldNumber = 4;
  ::google::protobuf::int64 versionnum() const;
  void set_versionnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.GetServiceStatus)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_steamid();
  inline void clear_has_steamid();
  inline void set_has_unknownfield();
  inline void clear_has_unknownfield();
  inline void set_has_versionnum();
  inline void clear_has_versionnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::internal::ArenaStringPtr steamid_;
  ::google::protobuf::internal::ArenaStringPtr unknownfield_;
  ::google::protobuf::int64 versionnum_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static GetServiceStatus* default_instance_;
};
// -------------------------------------------------------------------

class GetServiceStatusResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Frpg2RequestMessage.GetServiceStatusResponse) */ {
 public:
  GetServiceStatusResponse();
  virtual ~GetServiceStatusResponse();

  GetServiceStatusResponse(const GetServiceStatusResponse& from);

  inline GetServiceStatusResponse& operator=(const GetServiceStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const GetServiceStatusResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetServiceStatusResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetServiceStatusResponse* other);

  // implements Message ----------------------------------------------

  inline GetServiceStatusResponse* New() const { return New(NULL); }

  GetServiceStatusResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GetServiceStatusResponse& from);
  void MergeFrom(const GetServiceStatusResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetServiceStatusResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // required string steamid = 2;
  bool has_steamid() const;
  void clear_steamid();
  static const int kSteamidFieldNumber = 2;
  const ::std::string& steamid() const;
  void set_steamid(const ::std::string& value);
  void set_steamid(const char* value);
  void set_steamid(const char* value, size_t size);
  ::std::string* mutable_steamid();
  ::std::string* release_steamid();
  void set_allocated_steamid(::std::string* steamid);

  // required int64 unknownfield = 3;
  bool has_unknownfield() const;
  void clear_unknownfield();
  static const int kUnknownfieldFieldNumber = 3;
  ::google::protobuf::int64 unknownfield() const;
  void set_unknownfield(::google::protobuf::int64 value);

  // required int64 versionnum = 4;
  bool has_versionnum() const;
  void clear_versionnum();
  static const int kVersionnumFieldNumber = 4;
  ::google::protobuf::int64 versionnum() const;
  void set_versionnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Frpg2RequestMessage.GetServiceStatusResponse)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_steamid();
  inline void clear_has_steamid();
  inline void set_has_unknownfield();
  inline void clear_has_unknownfield();
  inline void set_has_versionnum();
  inline void clear_has_versionnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::internal::ArenaStringPtr steamid_;
  ::google::protobuf::int64 unknownfield_;
  ::google::protobuf::int64 versionnum_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Frpg2RequestMessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_Frpg2RequestMessage_2eproto();
  friend void protobuf_ShutdownFile_Frpg2RequestMessage_2eproto();

  void InitAsDefaultInstance();
  static GetServiceStatusResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestQueryLoginServerInfo

// required string steamid = 1;
inline bool RequestQueryLoginServerInfo::has_steamid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestQueryLoginServerInfo::set_has_steamid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestQueryLoginServerInfo::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestQueryLoginServerInfo::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
inline const ::std::string& RequestQueryLoginServerInfo::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfo::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
inline void RequestQueryLoginServerInfo::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
inline void RequestQueryLoginServerInfo::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}
inline ::std::string* RequestQueryLoginServerInfo::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestQueryLoginServerInfo::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfo::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfo.steamid)
}

// optional string unknownfield = 2;
inline bool RequestQueryLoginServerInfo::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestQueryLoginServerInfo::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestQueryLoginServerInfo::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestQueryLoginServerInfo::clear_unknownfield() {
  unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_unknownfield();
}
inline const ::std::string& RequestQueryLoginServerInfo::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  return unknownfield_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfo::set_unknownfield(const ::std::string& value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
inline void RequestQueryLoginServerInfo::set_unknownfield(const char* value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
inline void RequestQueryLoginServerInfo::set_unknownfield(const char* value, size_t size) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}
inline ::std::string* RequestQueryLoginServerInfo::mutable_unknownfield() {
  set_has_unknownfield();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  return unknownfield_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestQueryLoginServerInfo::release_unknownfield() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
  clear_has_unknownfield();
  return unknownfield_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfo::set_allocated_unknownfield(::std::string* unknownfield) {
  if (unknownfield != NULL) {
    set_has_unknownfield();
  } else {
    clear_has_unknownfield();
  }
  unknownfield_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), unknownfield);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfo.unknownfield)
}

// required int64 versionnum = 3;
inline bool RequestQueryLoginServerInfo::has_versionnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestQueryLoginServerInfo::set_has_versionnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestQueryLoginServerInfo::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestQueryLoginServerInfo::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
inline ::google::protobuf::int64 RequestQueryLoginServerInfo::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfo.versionnum)
  return versionnum_;
}
inline void RequestQueryLoginServerInfo::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfo.versionnum)
}

// -------------------------------------------------------------------

// RequestQueryLoginServerInfoResponse

// required int64 port = 1;
inline bool RequestQueryLoginServerInfoResponse::has_port() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestQueryLoginServerInfoResponse::set_has_port() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestQueryLoginServerInfoResponse::clear_has_port() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestQueryLoginServerInfoResponse::clear_port() {
  port_ = GOOGLE_LONGLONG(0);
  clear_has_port();
}
inline ::google::protobuf::int64 RequestQueryLoginServerInfoResponse::port() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.port)
  return port_;
}
inline void RequestQueryLoginServerInfoResponse::set_port(::google::protobuf::int64 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.port)
}

// required string serverip = 2;
inline bool RequestQueryLoginServerInfoResponse::has_serverip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestQueryLoginServerInfoResponse::set_has_serverip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestQueryLoginServerInfoResponse::clear_has_serverip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestQueryLoginServerInfoResponse::clear_serverip() {
  serverip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_serverip();
}
inline const ::std::string& RequestQueryLoginServerInfoResponse::serverip() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  return serverip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfoResponse::set_serverip(const ::std::string& value) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
inline void RequestQueryLoginServerInfoResponse::set_serverip(const char* value) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
inline void RequestQueryLoginServerInfoResponse::set_serverip(const char* value, size_t size) {
  set_has_serverip();
  serverip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}
inline ::std::string* RequestQueryLoginServerInfoResponse::mutable_serverip() {
  set_has_serverip();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  return serverip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestQueryLoginServerInfoResponse::release_serverip() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
  clear_has_serverip();
  return serverip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestQueryLoginServerInfoResponse::set_allocated_serverip(::std::string* serverip) {
  if (serverip != NULL) {
    set_has_serverip();
  } else {
    clear_has_serverip();
  }
  serverip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serverip);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestQueryLoginServerInfoResponse.serverip)
}

// -------------------------------------------------------------------

// RequestHandshake

// required string aescwckey = 1;
inline bool RequestHandshake::has_aescwckey() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestHandshake::set_has_aescwckey() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestHandshake::clear_has_aescwckey() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestHandshake::clear_aescwckey() {
  aescwckey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_aescwckey();
}
inline const ::std::string& RequestHandshake::aescwckey() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.RequestHandshake.aescwckey)
  return aescwckey_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestHandshake::set_aescwckey(const ::std::string& value) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
inline void RequestHandshake::set_aescwckey(const char* value) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
inline void RequestHandshake::set_aescwckey(const char* value, size_t size) {
  set_has_aescwckey();
  aescwckey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.RequestHandshake.aescwckey)
}
inline ::std::string* RequestHandshake::mutable_aescwckey() {
  set_has_aescwckey();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.RequestHandshake.aescwckey)
  return aescwckey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestHandshake::release_aescwckey() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.RequestHandshake.aescwckey)
  clear_has_aescwckey();
  return aescwckey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestHandshake::set_allocated_aescwckey(::std::string* aescwckey) {
  if (aescwckey != NULL) {
    set_has_aescwckey();
  } else {
    clear_has_aescwckey();
  }
  aescwckey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), aescwckey);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.RequestHandshake.aescwckey)
}

// -------------------------------------------------------------------

// RequestHandshakeResponse

// -------------------------------------------------------------------

// GetServiceStatus

// required int64 id = 1;
inline bool GetServiceStatus::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetServiceStatus::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetServiceStatus::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetServiceStatus::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 GetServiceStatus::id() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.id)
  return id_;
}
inline void GetServiceStatus::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.id)
}

// required string steamid = 2;
inline bool GetServiceStatus::has_steamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetServiceStatus::set_has_steamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetServiceStatus::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetServiceStatus::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
inline const ::std::string& GetServiceStatus::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatus::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.steamid)
}
inline void GetServiceStatus::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatus.steamid)
}
inline void GetServiceStatus::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatus.steamid)
}
inline ::std::string* GetServiceStatus::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatus.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetServiceStatus::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatus.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatus::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatus.steamid)
}

// optional string unknownfield = 3;
inline bool GetServiceStatus::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetServiceStatus::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetServiceStatus::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetServiceStatus::clear_unknownfield() {
  unknownfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_unknownfield();
}
inline const ::std::string& GetServiceStatus::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  return unknownfield_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatus::set_unknownfield(const ::std::string& value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
inline void GetServiceStatus::set_unknownfield(const char* value) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
inline void GetServiceStatus::set_unknownfield(const char* value, size_t size) {
  set_has_unknownfield();
  unknownfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}
inline ::std::string* GetServiceStatus::mutable_unknownfield() {
  set_has_unknownfield();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  return unknownfield_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetServiceStatus::release_unknownfield() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatus.unknownfield)
  clear_has_unknownfield();
  return unknownfield_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatus::set_allocated_unknownfield(::std::string* unknownfield) {
  if (unknownfield != NULL) {
    set_has_unknownfield();
  } else {
    clear_has_unknownfield();
  }
  unknownfield_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), unknownfield);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatus.unknownfield)
}

// required int64 versionnum = 4;
inline bool GetServiceStatus::has_versionnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetServiceStatus::set_has_versionnum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetServiceStatus::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetServiceStatus::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
inline ::google::protobuf::int64 GetServiceStatus::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatus.versionnum)
  return versionnum_;
}
inline void GetServiceStatus::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatus.versionnum)
}

// -------------------------------------------------------------------

// GetServiceStatusResponse

// required int64 id = 1;
inline bool GetServiceStatusResponse::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetServiceStatusResponse::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetServiceStatusResponse::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetServiceStatusResponse::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 GetServiceStatusResponse::id() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.id)
  return id_;
}
inline void GetServiceStatusResponse::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.id)
}

// required string steamid = 2;
inline bool GetServiceStatusResponse::has_steamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetServiceStatusResponse::set_has_steamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetServiceStatusResponse::clear_has_steamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetServiceStatusResponse::clear_steamid() {
  steamid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_steamid();
}
inline const ::std::string& GetServiceStatusResponse::steamid() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  return steamid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatusResponse::set_steamid(const ::std::string& value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
inline void GetServiceStatusResponse::set_steamid(const char* value) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
inline void GetServiceStatusResponse::set_steamid(const char* value, size_t size) {
  set_has_steamid();
  steamid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}
inline ::std::string* GetServiceStatusResponse::mutable_steamid() {
  set_has_steamid();
  // @@protoc_insertion_point(field_mutable:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  return steamid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetServiceStatusResponse::release_steamid() {
  // @@protoc_insertion_point(field_release:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
  clear_has_steamid();
  return steamid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceStatusResponse::set_allocated_steamid(::std::string* steamid) {
  if (steamid != NULL) {
    set_has_steamid();
  } else {
    clear_has_steamid();
  }
  steamid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), steamid);
  // @@protoc_insertion_point(field_set_allocated:Frpg2RequestMessage.GetServiceStatusResponse.steamid)
}

// required int64 unknownfield = 3;
inline bool GetServiceStatusResponse::has_unknownfield() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetServiceStatusResponse::set_has_unknownfield() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetServiceStatusResponse::clear_has_unknownfield() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetServiceStatusResponse::clear_unknownfield() {
  unknownfield_ = GOOGLE_LONGLONG(0);
  clear_has_unknownfield();
}
inline ::google::protobuf::int64 GetServiceStatusResponse::unknownfield() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.unknownfield)
  return unknownfield_;
}
inline void GetServiceStatusResponse::set_unknownfield(::google::protobuf::int64 value) {
  set_has_unknownfield();
  unknownfield_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.unknownfield)
}

// required int64 versionnum = 4;
inline bool GetServiceStatusResponse::has_versionnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetServiceStatusResponse::set_has_versionnum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetServiceStatusResponse::clear_has_versionnum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetServiceStatusResponse::clear_versionnum() {
  versionnum_ = GOOGLE_LONGLONG(0);
  clear_has_versionnum();
}
inline ::google::protobuf::int64 GetServiceStatusResponse::versionnum() const {
  // @@protoc_insertion_point(field_get:Frpg2RequestMessage.GetServiceStatusResponse.versionnum)
  return versionnum_;
}
inline void GetServiceStatusResponse::set_versionnum(::google::protobuf::int64 value) {
  set_has_versionnum();
  versionnum_ = value;
  // @@protoc_insertion_point(field_set:Frpg2RequestMessage.GetServiceStatusResponse.versionnum)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Frpg2RequestMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Frpg2RequestMessage_2eproto__INCLUDED
